cargo-features = ["strip"]

[package]
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]
edition = "2018"
license = "MIT"
name = "starlight"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
base64 = "0.13.0"
dotenv = "0.15.0"
futures = "0.3.17"
num_cpus = "1.13.0"
once_cell = "1.8"
persy = "1"
serde_json = "1"
sysinfo = "0.20.3"
thiserror = "1.0.29"
tracing = "0.1.26"
tracing-log = "0.1.2"

[dependencies.chrono]
default-features = false
features = ["std", "clock", "serde"]
version = "0.4.19"

[dependencies.clap]
git = "https://github.com/clap-rs/clap.git"

[dependencies.click-derive]
path = "./click-derive"

[dependencies.constella]
path = "./constella"

[dependencies.miette]
version = "3.0.1"
features = ["fancy"]

[dependencies.nebula]
path = "./nebula"

[dependencies.serde]
default-features = false
features = ["derive"]
version = "1.0.130"

[dependencies.structsy]
features = ["serde_info"]
git = "https://gitlab.com/tglman/structsy.git"

[dependencies.structsy-derive]
git = "https://gitlab.com/tglman/structsy.git"

[dependencies.star-utils]
git = "https://github.com/PyroTechniac/starlight-rs-utils.git"

[dependencies.supernova]
path = "./supernova"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "signal", "fs"]
version = "1.11.0"

[dependencies.tracing-subscriber]
features = ["fmt", "ansi"]
version = "0.2.20"

[dependencies.twilight-cache-inmemory]
default-features = false
git = "https://github.com/PyroTechniac/twilight.git"
rev = "05b7a38c952cb4da509054e788283f8fc0f7e47f"

[dependencies.twilight-embed-builder]
git = "https://github.com/PyroTechniac/twilight.git"
rev = "05b7a38c952cb4da509054e788283f8fc0f7e47f"

[dependencies.twilight-gateway]
default-features = false
features = ["zlib-simd", "metrics", "rustls", "tracing"]
git = "https://github.com/PyroTechniac/twilight.git"
rev = "05b7a38c952cb4da509054e788283f8fc0f7e47f"

[dependencies.twilight-http]
default-features = false
features = ["tracing", "simd-json", "rustls"]
git = "https://github.com/PyroTechniac/twilight.git"
rev = "05b7a38c952cb4da509054e788283f8fc0f7e47f"

[dependencies.twilight-mention]
git = "https://github.com/PyroTechniac/twilight.git"
rev = "05b7a38c952cb4da509054e788283f8fc0f7e47f"

[dependencies.twilight-model]
git = "https://github.com/PyroTechniac/twilight.git"
rev = "05b7a38c952cb4da509054e788283f8fc0f7e47f"

[dependencies.twilight-standby]
features = ["tracing"]
git = "https://github.com/PyroTechniac/twilight.git"
rev = "05b7a38c952cb4da509054e788283f8fc0f7e47f"

[dependencies.twilight-util]
default-features = false
features = ["snowflake"]
git = "https://github.com/PyroTechniac/twilight.git"
rev = "05b7a38c952cb4da509054e788283f8fc0f7e47f"

[dev-dependencies]
static_assertions = "1.1.0"

[build-dependencies]
built = "0.5.1"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
opt-level = 3
overflow-checks = false
panic = "abort"
strip = "symbols"

[profile.bench]
lto = "fat"

[workspace]
members = ["./click-derive", "./constella", "./nebula", "./supernova", "./star-test"]
