[package]
name = "starlight-rs"
version = "0.1.0"
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dotenv = "0.15.0"
futures = "0.3"
lazy_static = "1.4.0"
mimalloc = "0.1.25"
permission-calculator = { path = "./calculator" }
star-args = { path = "./args" }
tokio = { version = "1.6.0", features = ["macros", "rt-multi-thread"] }
twilight-cache-inmemory = "0.4"
twilight-gateway = { default-features = false, features = ["rustls", "simd-json", "simd-zlib"], version = "0.4" }
twilight-http = { default-features = false, features = ["simd-json"], version = "0.4" }
twilight-model = "0.4"
twilight-standby = "0.4"

[build-dependencies]
lang-build = { path = "./i18n-build" }

[profile.release]
lto = "fat"

[profile.bench]
lto = "fat"

[workspace]
members = [
    "./args",
    "./calculator",
    "./i18n-build"
]