cargo-features = ["strip"]

[package]
name = "starlight"
version = "0.1.0"
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
async-trait = "0.1.51"
base64 = "0.13.0"
dotenv = "0.15.0"
futures = "0.3.17"
once_cell = "1.8"
num_cpus = "1.13.0"
sysinfo = "0.20.3"
tracing = "0.1.26"
tracing-log = "0.1.2"

[dependencies.chrono]
version = "0.4.19"
default-features = false
features = ["std", "clock", "serde"]

[dependencies.clap]
git = "https://github.com/clap-rs/clap.git"

[dependencies.constella]
path = "./constella"

[dependencies.serde]
default-features = false
features = ["derive"]
version = "1.0.130"

[dependencies.structsy]
git = "https://gitlab.com/tglman/structsy.git"
features = ["serde_info"]

[dependencies.structsy-derive]
git = "https://gitlab.com/tglman/structsy.git"

[dependencies.star-utils]
git = "https://github.com/PyroTechniac/starlight-rs-utils.git"

[dependencies.tokio]
version = "1.11.0"
features = ["macros", "rt-multi-thread", "signal", "fs"]

[dependencies.tracing-subscriber]
version = "0.2.20"
features = ["fmt", "ansi"]

[dependencies.twilight-cache-inmemory]
git = "https://github.com/twilight-rs/twilight.git"
default-features = false

[dependencies.twilight-embed-builder]
git = "https://github.com/twilight-rs/twilight.git"

[dependencies.twilight-gateway]
git = "https://github.com/twilight-rs/twilight.git"
default-features = false
features = ["zlib-simd", "metrics", "rustls", "tracing"]

[dependencies.twilight-http]
git = "https://github.com/twilight-rs/twilight.git"
default-features = false
features = ["tracing", "simd-json", "rustls"]

[dependencies.twilight-mention]
git = "https://github.com/twilight-rs/twilight.git"

[dependencies.twilight-model]
git = "https://github.com/twilight-rs/twilight.git"

[dependencies.twilight-standby]
git = "https://github.com/twilight-rs/twilight.git"
features = ["tracing"]

[dependencies.twilight-util]
git = "https://github.com/twilight-rs/twilight.git"
default-features = false
features = ["snowflake"]

[dev-dependencies]
static_assertions = "1.1.0"

[build-dependencies]
built = "0.5.1"

[profile.release]
lto = "fat"
panic = "abort"
debug = true
strip = "symbols"
codegen-units = 1
overflow-checks = false
opt-level = 3

[profile.bench]
lto = "fat"

[workspace]
members = ["./constella"]