cargo-features = ["strip"]

[package]
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]
edition = "2021"
license = "MIT"
name = "starlight"
version = "0.1.0"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
opt-level = 3
overflow-checks = false
panic = "abort"
strip = "symbols"

[profile.bench]
lto = "fat"

[workspace]

[features]
default = []
docker = []
