[package]
name = "starlight-rs"
version = "0.1.0"
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dotenv = "0.15.0"
futures = "0.3"
serde_json = "1"
tracing = "0.1"

[dependencies.serde]
default-features = false
features = ["derive"]
version = "1"

[dependencies.star-args]
path = "./args"

[dependencies.star-error]
path = "./error"

[dependencies.star-lang]
path = "./lang"

[dependencies.tokio]
version = "1.6"
features = ["macros", "rt-multi-thread"]

[dependencies.tracing-subscriber]
version = "0.2"
features = ["fmt", "ansi"]

[dependencies.twilight-cache-inmemory]
git = "https://github.com/twilight-rs/twilight.git"
features = ["permission-calculator"]

[dependencies.twilight-gateway]
git = "https://github.com/twilight-rs/twilight.git"
default-features = false
features = ["rustls"]

[dependencies.twilight-http]
git = "https://github.com/twilight-rs/twilight.git"
features = ["tracing"]

[dependencies.twilight-mention]
git = "https://github.com/twilight-rs/twilight.git"

[dependencies.twilight-model]
git = "https://github.com/twilight-rs/twilight.git"

[dependencies.twilight-standby]
git = "https://github.com/twilight-rs/twilight.git"

[dependencies.twilight-util]
git = "https://github.com/twilight-rs/twilight.git"
features = ["snowflake"]

[dev-dependencies]
static_assertions = "1"

[profile.release]
lto = "fat"

[profile.bench]
lto = "fat"

[workspace]
members = [
    "./args",
    "./error",
    "./lang",
    "./test"
]