version: '2.4'
services:
    proxy:
        image: twilightrs/http-proxy:latest
        container_name: http-proxy
        environment:
            - DISCORD_TOKEN
            - HOST=0.0.0.0
            - PORT=3000
    starlight:
        build: .
        container_name: starlight
        depends_on:
            - proxy
        environment:
            - DISCORD_TOKEN
        tty: true