[package]
edition = "2021"
name = "supernova"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
thiserror = "1.0.3"

[dev-dependencies.miette]
version = "3.0.1"
features = ["fancy"]

[dev-dependencies.tokio]
version = "1"
default-features = false
features = ["rt", "macros"]
