[package]
name = "star-args"
version = "0.1.0"
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]
edition = "2018"

[dependencies]
uwl = "0.6.0"

[dependencies.twilight-command-parser]
git = "https://github.com/twilight-rs/twilight.git"