[package]
name = "star-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = { version = "3", features = ["fancy"] }
thiserror = "1.0.29"
semver = "1.0.4"