[package]
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]
description = "Starlight i18n file building"
edition = "2018"
license = "MIT"
name = "lang-build"
version = "0.1.0"

[dependencies]
serde_json = "1"